### ISSUE TITLE
It makes some NPCs' faces become red/white puppetized

### ISSUE THREAD

**Issue by sean-yang** [Oops19/TS4-CopyOutfits#2]
My version is 1.9.4-beta.

Check the image:

[https://imgur.com/a/6PV0sqE](url)

**Comment by psofomar** [comment]
Mine had done this too (red/white checker pattern on entire body + head and no amount of removing outfit parts in CAS was making it go away) each time a sim was generated via randomization. I removed the mod and it fixed the issue. 

I'll try 1.9.5 today and see if I can generate sims without issue.

Edit: the 1.9.5 version resolved my issue.

**Comment by Oops19** [comment]
v.1.9.4 still has some CAS parts tagged for random. These reference UGC full body skins to optionally colorize the mannequins. The UGC is by other creators an in case it's not installed the mod detects it but unfortunately not the game. 
With v1.9.5 these CAS parts are no longer available for random.
